#KAFKA
kafka:
  bootstrapServer: 172.19.178.136:9092
  topic:
    restaurant:
      status-update: UPDATE_STATUS
      storename: status-store

server:
  port: 8091

application:
  name: JET

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
